server:
  port: 8080

spring:
  application:
    name: gateway-auth-service
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: gateway-auth-service-route
          uri: lb://gateway-auth-service  # This routes the user requests to the actual user service
          predicates:
            - Path=/api/v2/auth/**  # Access user-related endpoints via this path

        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/v2/product/**

        - id: email-sender-service-route
          uri: lb://email-sender-service
          predicates:
            - Path=/api/v2/email/**

        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/order-service/**

        - id: credit-card-service-route
          uri: lb://credit-card-service
          predicates:
            - Path=/credit-card-service/**

        - id: chat-gpt-service-route
          uri: lb://chat-gpt-service
          predicates:
            - Path=/chat-gpt-service/**

  config:
    import:
      - .env[.properties]

  r2dbc:
    url: ${R2DBC_URL}
    username: ${USER_NAME_DB}
    password: ${PASSWORD_DB}

  #Liquibase configuration
  liquibase:
    url: ${JDBC_URL}
    user: ${USER_NAME_DB}
    password: ${PASSWORD_DB}
    enabled: true


#Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE_EUREKA}

#JWT token configuration
back-end:
  security:
    jwt:
      access:
        expiration: ${JWT_ACCESS_EXPIRATION}
      refresh:
        expiration: ${JWT_REFRESH_EXPIRATION}
    # This list is used to exclude paths from authentication processing when security configuration is enabled
    auth-whitelist: ${AUTH_WHITELIST}
    custom:
      allowed:
        paths: ${ALLOWED_PATHS:}

#Frontend uri
front-end:
  uri: ${FRONT_END_URI}

#Logging configuration
logging:
  level:
    org.springframework.r2dbc: DEBUG
    liquibase: DEBUG
    root: INFO
    ua.dev.food.fast.service: DEBUG
  file:
    name: logger.log

# Testing configuration
---
spring:
  config:
    activate:
      on-profile: test
    import:
      - .env[.properties]
  r2dbc:
    url: ${R2DBC_TEST_URL}
    username: test
    password: test
  liquibase:
    url: ${JDBC_TEST_URL}
    user: test
    password: test
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
back-end:
  security:
    jwt:
      access:
        expiration: ${JWT_ACCESS_EXPIRATION}
      refresh:
        expiration: ${JWT_REFRESH_EXPIRATION}
---